name: nuvexadb
description: Flutter / Dart SDK for NuvexaDB. Thin dart:ffi wrapper over the Native AOT C ABI.
version: 1.0.7
repository: https://github.com/nuvyntralabs/NuvexaDB
homepage: https://github.com/nuvyntralabs/NuvexaDB

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  ffi: ^2.1.4

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
