<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <AssemblyName>nuvexa</AssemblyName>
    <RootNamespace>Nuventra.NuvexaDB.Native</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StackTraceSupport>false</StackTraceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('ios'))">
    <NativeLib>Shared</NativeLib>
    <PublishAotUsingRuntimePack>true</PublishAotUsingRuntimePack>
  </PropertyGroup>

  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('linux-bionic'))">
    <LinkerArg Include="-Wl,--undefined-version" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nuventra.NuvexaDB\Nuventra.NuvexaDB.csproj" />
  </ItemGroup>

</Project>
